version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "5173"
    environment:
      - VITE_API_BASE_URL=https://localhost/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - ./backend:/var/www/html
      - storage_data:/var/www/html/storage   # 🔑 persistent storage
      - ./backups:/backups                   # ✅ shared backups folder
      - ./backup/backup.sh:/backup.sh               # ✅ make script available
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:changeme
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=document_vault_app
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: document_vault_app
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  caddy:
    image: caddy:2-alpine
    container_name: document_vault_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend

  backup:
    build:
      context: ./backup
      dockerfile: Dockerfile
    container_name: document_vault_backup
    depends_on:
      - db
      - backend
    volumes:
      - ./backups:/backups
      - ./backend/storage/app:/var/www/html/storage/app:ro
      - ./backup/backup.sh:/backup.sh               # ✅ ensure script exists here too
    environment:
      - TZ=Asia/Manila
    networks:
      - default

volumes:
  db_data:
  storage_data:      # 🔑 shared file storage
  caddy_data:
  caddy_config:
